# Generated by Django 3.0.8 on 2020-09-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品名')),
                ('thumbnail', models.ImageField(upload_to='media/', verbose_name='商品画像')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='商品価格')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('description', models.TextField(verbose_name='商品説明')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='商品作成日')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='商品更新日')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
